# markdownlint-cli2 configuration for Git-flavored Markdown
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

config:
  MD033: false
  MD041: false

  MD013:
    line_length: 120
    tables: false
    code_blocks: false
    headings: false

  MD004:
    style: "dash"

  MD007:
    indent: 2

  MD049:
    style: "asterisk"

  MD050:
    style: "asterisk"

globs:
  - "!**/.*/**/*.md"

fix: true
